#controller_joint_names: ['', 'joint01', 'joint02', 'joint03', 'joint04', 'joint05', 'joint06', 'joint07', 'joint08', ]

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
joint01_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint01
    pid: {p: 1.0, i: 0.05, d: 0.0}
    
joint02_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint02
    pid: {p: 4.0, i: 0.05, d: 0.0}
    
joint03_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint03
    pid: {p: 3.0, i: 0.05, d: 0.0}
    
joint04_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint04
    pid: {p: 2.0, i: 0.05, d: 0.0}
    
joint05_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint05
    pid: {p: 2.0, i: 0.05, d: 0.0}
    
joint06_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint06
    pid: {p: 2.0, i: 0.05, d: 0.0}
    
joint07_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint07
    pid: {p: 1.0, i: 0.05, d: 0.0}
    
joint08_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint08
    pid: {p: 1.0, i: 0.05, d: 0.0}