controller_joint_names: ['', 'joint01', 'joint02', 'joint03', 'joint04', 'joint05', 'joint06', 'joint07', 'joint08', 'joint09', 'joint10', 
'joint11', 'joint12', 'joint13', 'joint14', 'joint15', 'joint16', 'joint17', 'joint18', 'joint19', 'joint20', 
'joint21', 'joint22', 'joint23', 'joint24', 'joint25', 'joint26', 'joint27', 'joint28', 'joint29', 'joint30',
'joint31', 'joint32', 'joint33', 'joint34', 'joint35', 'joint36', 'joint37', 'joint38', 'joint39', 'joint40',
'joint41', 'joint42', 'joint43', 'joint44', 'joint45', 'joint46', 'joint47', 'joint48', 'joint49', 'joint50', ]

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
joint01_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint01
    pid: {p: 0.01, i: 0, d: 0.0}
    
joint02_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint02
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint03_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint03
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint04_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint04
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint05_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint05
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint06_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint06
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint07_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint07
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint08_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint08
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint09_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint09
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint10
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint11
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint12
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint13_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint13
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint14_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint14
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint15_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint15
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint16_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint16
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint17_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint17
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint18_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint18
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint19_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint19
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint20_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint20
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint21_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint21
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint22_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint22
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint23_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint23
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint24_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint24
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint25_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint25
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint26_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint26
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint27_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint27
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint28_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint28
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint29_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint29
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint30_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint30
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint31_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint31
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint32_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint32
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint33_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint33
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint34_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint34
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint35_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint35
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint36_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint36
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint37_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint37
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint38_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint38
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint39_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint39
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint40_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint40
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint41_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint41
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint42_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint42
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint43_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint43
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint44_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint44
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint45_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint45
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint46_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint46
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint47_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint47
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint48_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint48
    pid: {p: 0.01, i: 0.0, d: 0.0}

joint49_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint49
    pid: {p: 0.01, i: 0.0, d: 0.0}
    
joint50_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint50
    pid: {p: 0.01, i: 0.0, d: 0.0}